### ISSUE TITLE
Place-holder text disappearing after rapid user input

### ISSUE THREAD

**Issue by ILM126** [chao-master/TSSSF-App#10]
Was just giving this a try when I noticed that the place-holder text disappears whenever I rapidly enter text like this. Already reproduced it twice, as the place-holder text appeared a bit afterwards. Which I'll explain below.

![screenshot_560](https://cloud.githubusercontent.com/assets/7699696/15805957/8c8271ae-2b77-11e6-9292-07802837978e.png)

This is reproduced if you don't select the text and delete it.

![screenshot_559](https://cloud.githubusercontent.com/assets/7699696/15805956/8c76c75a-2b77-11e6-8d58-005c7ffef881.png)

The only way to fix this is to select the text, and then deleting it from the card. This causes the place-holder text to reappear!

![screenshot_561](https://cloud.githubusercontent.com/assets/7699696/15805979/f574b26c-2b77-11e6-8d8f-0363f7cdcc8e.png)
![screenshot_562](https://cloud.githubusercontent.com/assets/7699696/15805980/f587b9fc-2b77-11e6-949b-afbcaa1cbceb.png)

Hope that this helps!
Saw this via Juby's page, such an awesome web app :smile: :+1: 
Keep up the good work ^_^

**Comment by chao-master** [comment]
@ILM126 Couldn't recreate in google chrome v51 on linux, which browser and device is this on?

**Comment by ILM126** [comment]
@chao-master Well, I just tired it in Chrome 51.0.2704.84m on Windows. It seems to work fine now, I think I was on an older version of chrome....
But the problem seems to have disappeared, so I'm closing this issue now.
