### ISSUE TITLE
Picture Upload Icons not Appearing on Mobile

### ISSUE THREAD

**Issue by MrQuallzin** [chao-master/TSSSF-App#2]
The two little card image things to click on do not appear on my phone as they should. This could be phone/Chrome version specific as they appear when emulating mobile pages via Chrome on my computer.

**Comment by chao-master** [comment]
It appears font awesome was missing from the project, though this just raises more questions such as:
why on both did both our pcs not care? (though those are not for here)
Fixed in a213e41f
